# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161201_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirrurl',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='kirrurl',
            name='updated',
        ),
    ]
